docs: add doc for casbin k8s-gatekeeper
casbin/casbin-website-v2 pull request #82
Opened 2022-08-29 04:53 UTC by ComradeProgrammer

docs: add doc for casbin k8s-gatekeeper

2022-08-29 08:01 UTC, hsluoyz requested changes

2022-08-29 08:01 UTC, hsluoyz commented on docs/K8sGateKeeper.mdx
> +## 0. What is Casbin K8s-Gatekeeper
start from 1

2022-08-29 08:01 UTC, hsluoyz commented
@Selflocking plz review

2022-08-29 09:00 UTC, Selflocking commented on docs/K8sGateKeeper.mdx
> +```
```suggestion
```shell
```

2022-08-29 09:00 UTC, Selflocking commented on docs/K8sGateKeeper.mdx
> +```
```suggestion
```shell
```

2022-08-29 09:06 UTC, Selflocking commented on docs/K8sGateKeeper.mdx
> +```
```suggestion
```csv
```

2022-08-29 09:06 UTC, Selflocking commented on docs/K8sGateKeeper.mdx
> +```
```suggestion
```ini
```

2022-08-29 09:06 UTC, Selflocking commented on docs/K8sGateKeeper.mdx
> +```
```suggestion
```ini
```

2022-08-29 09:06 UTC, Selflocking commented on docs/K8sGateKeeper.mdx
> +```
```suggestion
```csv
```

2022-08-29 09:06 UTC, Selflocking commented on docs/K8sGateKeeper.mdx
> +```
```suggestion
```shell
```

2022-08-29 09:19 UTC, Selflocking commented on docs/K8sGateKeeper.mdx
> +Copy your system's openssl config file for temporary use. You can use `openssl version -a` to find out the location of the config file.
It's better to use the filename of the config file instead of just using `the config file`.

2022-08-29 09:19 UTC, Selflocking commented on docs/K8sGateKeeper.mdx
> +```
```suggestion
```ini
```

2022-08-30 11:57 UTC, hsluoyz commented
@Selflocking

2022-08-30 13:58 UTC, Selflocking requested changes

2022-08-30 13:58 UTC, Selflocking commented on docs/K8sGateKeeper.mdx
> +:::note title="Note"
It's all my fault.
refer to https://docusaurus.io/docs/markdown-features/admonitions
The proper format should be:
```mdx
:::note title(optional)

content

:::
```

`title` is optional.
It is necessary to leave two blank lines. becase: https://github.com/casbin/casbin-website-v2/pull/41

In addition to `note`, you can also use `tip`, `info`, `caution`, `danger`.
![image](https://user-images.githubusercontent.com/53544726/187452275-4072bd2c-f026-4bcb-8ec9-d5fbcfb264bc.png)

2022-08-30 13:58 UTC, Selflocking commented on docs/K8sGateKeeper.mdx
> +Admission webhooks in K8s are HTTP callbacks that receive 'admission requests' and do something with them. In particular, K8s-gatekeeper is a special type of admission webhoook: 'ValidatingAdmissionW
```suggestion
Admission webhooks in K8s are HTTP callbacks that receive 'admission requests' and do something with them. In particular, K8s-gatekeeper is a special type of admission webhoook: 'ValidatingAdmissionWebhook', which can decide whether to accept or reject this admission request or not. As for admission requests, they are HTTP requests describing an operation on specified resources of K8s (for example, creating/deleting a deployment). For more about admission webhooks, see [K8s official doc](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#what-are-admission-webhooks)
```

2022-08-30 13:58 UTC, Selflocking commented on docs/K8sGateKeeper.mdx
> +:::note title="Note"
needs to be changed like above

2022-08-30 13:58 UTC, Selflocking commented on docs/K8sGateKeeper.mdx
> +```golang
Unfortunately `golang` doesn't work, `go` works.
So we need change it.

2022-08-30 13:58 UTC, Selflocking commented on docs/K8sGateKeeper.mdx
> +If you don't know what is casbin funtion, see [Function]</docs/function> for more information.
```suggestion
If you don't know what is casbin funtion, see [Function](/docs/function) for more information.
```

2022-09-07 12:03 UTC, hsluoyz commented
@ComradeProgrammer

2022-09-08 03:54 UTC, hsluoyz approved these changes

2022-09-08 04:42 UTC, merged